version: "3"
services:
  streams:
    restart: always
    image: mongo
    container_name: "dbStreams"
    environment:
      - MONGO_INITDB_DATABASE=dbStreams
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=welcome1
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

volumes:
  mongodb:
  mongodb_config:

